### ISSUE TITLE
Controlling Sensors and irrigation system on mobile phone.

### ISSUE THREAD

**Issue by OrhanOnar** [Smart-flowerpot/Smart-Flowerpot-Arduino#6]
As a user;

I want to check my plants information and  irrigation system with my mobile phone.

**Comment by musaunal** [comment]
commit no 6f6728435ed1ac1ca40cb01f187ca6a2f731e73b  ile çözüldü


![tel jpeg](https://user-images.githubusercontent.com/17799253/51800465-0c3bae80-2240-11e9-9ae0-e1906bcb97af.jpg)
